name: 'nfl_dbt'
version: '1.0'

profile: 'nfl'

source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

require-dbt-version: ">=0.15.1"

quoting:
    database: true
    identifier: false
    schema: false

models:
    persist_docs:
        relation: true

    nfl_dbt:
        staging:
            schema: staging
        analysis:
            schema: analysis
    vars:
        dbt_date:time_zone: 'UTC'
        incremental_days: 30